// src/utils/mockData.js

export const initialPatients = [
  {
    id: 'rec-001',
    patient_id: 'P-101-2024',
    data_collection_date: '2026-08-10',
    inclusion_age_18: true,
    inclusion_dialysis_3months: true,
    inclusion_dialysis_center: true,
    inclusion_informed_consent: true,
    exclusion_bleeding: false,
    exclusion_transfusion: false,
    exclusion_hematologic_malignancy: false,
    exclusion_chemotherapy: false,
    exclusion_pregnancy: false,
    eligibility_status: 'Included',
    age_years: 54,
    gender: 'Male',
    marital_status: 'Married',
    education_level: 'Secondary',
    employment_status: 'Unemployed-Retired',
    residence_type: 'Urban',
    weight_kg: 76.5,
    height_cm: 172,
    esrd_cause: 'Diabetic Nephropathy',
    esrd_cause_other: '',
    ckd_duration_years: 6,
    comorbidities: ['Diabetes Mellitus', 'Hypertension'],
    hospitalization_count: '1 time',
    dialysis_duration_value: 24,
    dialysis_duration_unit: 'Months',
    dialysis_sessions_per_week: '3 sessions/week',
    session_duration: '4 hours',
    vascular_access_type: 'Arteriovenous Fistula (AVF)',
    kt_v: 1.35,
    hemoglobin_g_dl: 9.4,
    anemia_severity: 'Moderate',
    ferritin_ng_ml: 280,
    tsat_percent: 22,
    albumin_g_dl: 3.8,
    crp_mg_l: 6.2,
    ipth_pg_ml: 240,
    esa_therapy: true,
    esa_dose_frequency: 'Epoetin alfa 4000 IU twice weekly',
    iron_supplementation: 'Intravenous (IV) Iron',
    vitamin_b12: true,
    folic_acid: true,
    blood_transfusion_6months: false,
    transfusion_units_count: null,
    doctor_name: 'Dr. Mohammed Al-Husseini',
    created_at: '2026-08-10T09:30:00Z',
  },
  {
    id: 'rec-002',
    patient_id: 'P-102-2024',
    data_collection_date: '2026-08-12',
    inclusion_age_18: true,
    inclusion_dialysis_3months: true,
    inclusion_dialysis_center: true,
    inclusion_informed_consent: true,
    exclusion_bleeding: false,
    exclusion_transfusion: false,
    exclusion_hematologic_malignancy: false,
    exclusion_chemotherapy: false,
    exclusion_pregnancy: false,
    eligibility_status: 'Included',
    age_years: 48,
    gender: 'Female',
    marital_status: 'Married',
    education_level: 'University or Higher',
    employment_status: 'Employed (Full-time)',
    residence_type: 'Urban',
    weight_kg: 62.0,
    height_cm: 160,
    esrd_cause: 'Hypertensive Nephropathy',
    esrd_cause_other: '',
    ckd_duration_years: 4,
    comorbidities: ['Hypertension'],
    hospitalization_count: 'None',
    dialysis_duration_value: 14,
    dialysis_duration_unit: 'Months',
    dialysis_sessions_per_week: '3 sessions/week',
    session_duration: '4 hours',
    vascular_access_type: 'Arteriovenous Fistula (AVF)',
    kt_v: 1.45,
    hemoglobin_g_dl: 10.8,
    anemia_severity: 'Mild',
    ferritin_ng_ml: 410,
    tsat_percent: 28,
    albumin_g_dl: 4.1,
    crp_mg_l: 3.1,
    ipth_pg_ml: 180,
    esa_therapy: true,
    esa_dose_frequency: 'Darbepoetin 30 mcg weekly',
    iron_supplementation: 'Intravenous (IV) Iron',
    vitamin_b12: false,
    folic_acid: true,
    blood_transfusion_6months: false,
    transfusion_units_count: null,
    doctor_name: 'Dr. Mohammed Al-Husseini',
    created_at: '2026-08-12T11:15:00Z',
  },
  {
    id: 'rec-003',
    patient_id: 'P-103-2024',
    data_collection_date: '2026-08-14',
    inclusion_age_18: true,
    inclusion_dialysis_3months: true,
    inclusion_dialysis_center: true,
    inclusion_informed_consent: true,
    exclusion_bleeding: false,
    exclusion_transfusion: false,
    exclusion_hematologic_malignancy: false,
    exclusion_chemotherapy: false,
    exclusion_pregnancy: false,
    eligibility_status: 'Included',
    age_years: 67,
    gender: 'Male',
    marital_status: 'Widowed',
    education_level: 'Primary-Intermediate',
    employment_status: 'Unemployed-Retired',
    residence_type: 'Rural',
    weight_kg: 84.0,
    height_cm: 168,
    esrd_cause: 'Polycystic Kidney Disease (PKD)',
    esrd_cause_other: '',
    ckd_duration_years: 12,
    comorbidities: ['Hypertension', 'Cardiovascular Disease (CVD)'],
    hospitalization_count: '≥ 2 times',
    dialysis_duration_value: 36,
    dialysis_duration_unit: 'Months',
    dialysis_sessions_per_week: '3 sessions/week',
    session_duration: '3.5 hours',
    vascular_access_type: 'Permcath (Tunneled Cuffed Catheter)',
    kt_v: 1.15,
    hemoglobin_g_dl: 7.4,
    anemia_severity: 'Severe',
    ferritin_ng_ml: 120,
    tsat_percent: 14,
    albumin_g_dl: 3.2,
    crp_mg_l: 14.8,
    ipth_pg_ml: 450,
    esa_therapy: true,
    esa_dose_frequency: 'Epoetin alfa 10000 IU weekly',
    iron_supplementation: 'Intravenous (IV) Iron',
    vitamin_b12: true,
    folic_acid: true,
    blood_transfusion_6months: true,
    transfusion_units_count: 2,
    doctor_name: 'Dr. Mohammed Al-Husseini',
    created_at: '2026-08-14T14:20:00Z',
  },
  {
    id: 'rec-004',
    patient_id: 'P-104-2024',
    data_collection_date: '2026-08-15',
    inclusion_age_18: true,
    inclusion_dialysis_3months: false,
    inclusion_dialysis_center: true,
    inclusion_informed_consent: true,
    exclusion_bleeding: false,
    exclusion_transfusion: false,
    exclusion_hematologic_malignancy: false,
    exclusion_chemotherapy: false,
    exclusion_pregnancy: false,
    eligibility_status: 'Excluded',
    age_years: 39,
    gender: 'Female',
    marital_status: 'Married',
    education_level: 'University or Higher',
    employment_status: 'Employed (Part-time)',
    residence_type: 'Urban',
    weight_kg: 58.0,
    height_cm: 165,
    esrd_cause: 'Glomerulonephritis',
    esrd_cause_other: '',
    ckd_duration_years: 2,
    comorbidities: ['Hypertension'],
    hospitalization_count: 'None',
    dialysis_duration_value: 1.5,
    dialysis_duration_unit: 'Months',
    dialysis_sessions_per_week: '2 sessions/week',
    session_duration: '3 hours',
    vascular_access_type: 'Temporary Non-tunneled Catheter',
    kt_v: 1.05,
    hemoglobin_g_dl: 12.2,
    anemia_severity: 'Non-anemic',
    ferritin_ng_ml: 320,
    tsat_percent: 24,
    albumin_g_dl: 4.2,
    crp_mg_l: 2.4,
    ipth_pg_ml: 150,
    esa_therapy: false,
    esa_dose_frequency: '',
    iron_supplementation: 'Oral Iron',
    vitamin_b12: false,
    folic_acid: true,
    blood_transfusion_6months: false,
    transfusion_units_count: null,
    doctor_name: 'Dr. Mohammed Al-Husseini',
    created_at: '2026-08-15T10:00:00Z',
  },
];

export const defaultDoctor = {
  id: 'doc-001',
  full_name: 'Dr. Mohammed Al-Husseini',
  email: 'dr.mohammed@ibnsina.med',
  institution: 'Ibn Sina Center for Dialysis & Kidney Disease',
  title: 'Consultant Nephrologist & Lead Investigator',
};
