// src/utils/pdfGenerator.js
import { PDFDocument, PDFPage } from '@react-native-pdf-lib/src';
import Share from 'react-native-share';
import { formatDate, formatNumber, prepareDataForExport } from './calculations';
import { colors, typography } from '../styles/theme';

/**
 * Generate PDF from patient data
 * @param {object} formData - Complete patient form data
 * @param {string} doctorName - Name of doctor
 * @returns {Promise<string>} - Path to generated PDF file
 */
export const generatePatientPDF = async (formData, doctorName = 'Dr. Unknown') => {
  try {
    // Prepare data for display
    const exportData = prepareDataForExport(formData);

    // Create PDF document
    const pdfDocument = PDFDocument.createNew();

    // Add Header
    pdfDocument
      .addPage('US-Letter')
      .setTextColor(colors.primary)
      .setFont('Helvetica-Bold', 24)
      .drawText('ANEMIA RESEARCH STUDY', 50, 50)
      .setTextColor(colors.textPrimary)
      .setFont('Helvetica', 10)
      .drawText(`Data Collection Report`, 50, 80)
      .drawText(`Date: ${new Date().toLocaleDateString()}`, 50, 95)
      .setDrawColor(colors.primary)
      .drawRect(50, 105, 500, 1)

      // Patient Information Section
      .setFont('Helvetica-Bold', 14)
      .setTextColor(colors.primary)
      .drawText('PATIENT INFORMATION', 50, 130)

      .setFont('Helvetica', 10)
      .setTextColor(colors.textPrimary)
      .drawText(`Patient ID: ${exportData.patientId}`, 50, 150)
      .drawText(`Collection Date: ${exportData.collectionDate}`, 50, 165)
      .drawText(`Doctor: ${doctorName}`, 50, 180)

      // Eligibility Status Badge
      .setFont('Helvetica-Bold', 11)
      .setTextColor(
        exportData.eligibilityStatus === 'Included' ? colors.success : colors.error
      )
      .drawText(`Status: ${exportData.eligibilityStatus}`, 50, 200);

    // Add Demographics Section
    addSectionToPDF(
      pdfDocument,
      'DEMOGRAPHICS & SOCIOECONOMIC DATA',
      230,
      [
        ['Age', exportData.demographics.age],
        ['Gender', exportData.demographics.gender],
        ['Marital Status', exportData.demographics.maritalStatus],
        ['Education Level', exportData.demographics.educationLevel],
        ['Employment Status', exportData.demographics.employmentStatus],
        ['Residence Type', exportData.demographics.residenceType],
        ['Weight', exportData.anthropometry.weight],
        ['Height', exportData.anthropometry.height],
      ]
    );

    // Add Medical History Section
    addSectionToPDF(
      pdfDocument,
      'MEDICAL HISTORY & COMORBIDITIES',
      380,
      [
        ['ESRD Cause', exportData.medicalHistory.esrdCause],
        ['CKD Duration', exportData.medicalHistory.ckdDuration],
        ['Comorbidities', exportData.medicalHistory.comorbidities],
        ['Hospitalizations (Last Year)', exportData.medicalHistory.hospitalization],
      ]
    );

    // Add Dialysis Parameters Section
    addSectionToPDF(
      pdfDocument,
      'DIALYSIS PARAMETERS',
      480,
      [
        ['Dialysis Duration', exportData.dialysisParameters.duration],
        ['Sessions Per Week', exportData.dialysisParameters.sessionsPerWeek],
        ['Session Duration', exportData.dialysisParameters.sessionDuration],
        ['Vascular Access Type', exportData.dialysisParameters.vasularAccessType],
        ['Kt/V', exportData.dialysisParameters.ktV],
      ]
    );

    // Add Laboratory Results Section
    addSectionToPDF(
      pdfDocument,
      'LABORATORY RESULTS',
      580,
      [
        ['Hemoglobin', exportData.laboratoryResults.hemoglobin],
        ['Anemia Severity', exportData.laboratoryResults.anemiaSeverity],
        ['Serum Ferritin', exportData.laboratoryResults.ferritin],
        ['TSAT', exportData.laboratoryResults.tsat],
        ['Albumin', exportData.laboratoryResults.albumin],
        ['CRP', exportData.laboratoryResults.crp],
        ['iPTH', exportData.laboratoryResults.ipth],
      ]
    );

    // Add Treatment Section
    addSectionToPDF(
      pdfDocument,
      'TREATMENTS',
      680,
      [
        ['ESA Therapy', exportData.treatments.esaTherapy],
        ['Iron Supplementation', exportData.treatments.ironSupplementation],
        ['Vitamin B12', exportData.treatments.vitaminB12],
        ['Folic Acid', exportData.treatments.folicAcid],
        ['Blood Transfusion (6 months)', exportData.treatments.bloodTransfusion],
      ]
    );

    // Add footer
    pdfDocument
      .setFont('Helvetica-Oblique', 8)
      .setTextColor(colors.textTertiary)
      .drawText(
        `Generated by Anemia Research Study App - ${new Date().toLocaleString()}`,
        50,
        770
      );

    // Save PDF
    const pdfFile = await pdfDocument.save();

    return {
      success: true,
      filePath: pdfFile,
      fileName: `Patient_${exportData.patientId}_${formatDate(
        exportData.collectionDate
      ).replace(/\//g, '-')}.pdf`,
    };
  } catch (error) {
    console.error('PDF generation error:', error);
    return {
      success: false,
      error: error.message,
    };
  }
};

/**
 * Helper function to add a section to PDF
 */
function addSectionToPDF(pdfDocument, title, yPosition, dataArray) {
  pdfDocument
    .setFont('Helvetica-Bold', 12)
    .setTextColor(colors.primary)
    .drawText(title, 50, yPosition);

  let currentY = yPosition + 20;

  // Add data rows
  dataArray.forEach(([label, value]) => {
    pdfDocument
      .setFont('Helvetica-Bold', 9)
      .setTextColor(colors.textSecondary)
      .drawText(`${label}:`, 70, currentY)
      .setFont('Helvetica', 9)
      .setTextColor(colors.textPrimary)
      .drawText(`${value || 'N/A'}`, 200, currentY);

    currentY += 12;
  });

  // Add divider line
  pdfDocument
    .setDrawColor(colors.divider)
    .drawRect(50, currentY + 5, 500, 0.5);
}

/**
 * Share PDF file using native share dialog
 * @param {string} filePath - Path to PDF file
 * @param {string} fileName - File name
 * @returns {Promise<boolean>}
 */
export const sharePDF = async (filePath, fileName) => {
  try {
    await Share.open({
      url: `file://${filePath}`,
      filename: fileName,
      title: 'Share Patient Report',
      message: 'Here is the patient data report',
      type: 'application/pdf',
    });

    return {
      success: true,
      message: 'PDF shared successfully',
    };
  } catch (error) {
    console.error('Share PDF error:', error);
    if (error.code !== 'E_CANCELLED') {
      return {
        success: false,
        error: error.message,
      };
    }
  }
};

/**
 * Download PDF file
 * @param {string} filePath - Path to PDF file
 * @param {string} fileName - File name
 * @returns {Promise<boolean>}
 */
export const downloadPDF = async (filePath, fileName) => {
  try {
    // For React Native, files are typically saved to app's document directory
    // Implementation depends on your app's file storage setup
    console.log(`PDF saved to: ${filePath}`);
    return {
      success: true,
      filePath,
      fileName,
      message: 'PDF downloaded successfully',
    };
  } catch (error) {
    console.error('Download PDF error:', error);
    return {
      success: false,
      error: error.message,
    };
  }
};

export default {
  generatePatientPDF,
  sharePDF,
  downloadPDF,
};
